<?php

declare(strict_types=1);

namespace App\Users\Domain\ValueObject;

use App\Users\Domain\Exception\InvalidOneTimePassword;

/**
 * A plaintext one-time login credential (LRA-213).
 *
 * Held only transiently: generated by an {@see \App\Users\Domain\OneTimePasswordGenerator}
 * adapter, shown to the issuing staff member once, then hashed and discarded.
 * Never persisted and never logged.
 */
final readonly class OneTimePassword
{
    public const int LENGTH = 12;

    public string $value;

    private function __construct(string $value)
    {
        $this->value = $value;
    }

    public static function of(string $value): self
    {
        $length = mb_strlen($value, 'UTF-8');
        if ($length !== self::LENGTH) {
            throw InvalidOneTimePassword::length($length, self::LENGTH);
        }

        if (preg_match('/\s/', $value) === 1) {
            throw InvalidOneTimePassword::whitespace();
        }

        return new self($value);
    }

    public function equals(self $other): bool
    {
        return hash_equals($this->value, $other->value);
    }
}
