<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * LRA-19: swap user.id from int IDENTITY to a 36-char UUID v7 string column.
 *
 * Destructive on purpose — there is no production data yet (the milestone
 * has only shipped the login skeleton). Any locally-seeded staff accounts
 * are recreated via `bin/console app:create-user` after migration.
 */
final class Version20260523140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Swap user.id from int IDENTITY to a 36-char UUID v7 string column (LRA-19).';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'Migration uses PostgreSQL-specific SQL (quoted "user", JSON, TIMESTAMP(0) WITHOUT TIME ZONE).',
        );

        // Drop the entire table — there is no production data to preserve,
        // and the schema change (PK type + drop of identity sequence) is
        // simpler to express as a recreate than a multi-step in-place
        // migration.
        $this->addSql('DROP TABLE "user"');

        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (
                id CHAR(36) NOT NULL,
                username VARCHAR(180) NOT NULL,
                roles JSON NOT NULL,
                password VARCHAR(255) NOT NULL,
                is_active BOOLEAN DEFAULT true NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'Migration uses PostgreSQL-specific SQL.',
        );

        $this->addSql('DROP TABLE "user"');
        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                username VARCHAR(180) NOT NULL,
                roles JSON NOT NULL,
                password VARCHAR(255) NOT NULL,
                is_active BOOLEAN DEFAULT true NOT NULL,
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON "user" (username)');
    }
}
