<?php

declare(strict_types=1);

namespace App\Administration\Domain;

use App\Administration\Domain\Event\AdministratorGranted;
use App\Administration\Domain\Event\AdministratorRankChanged;
use App\Administration\Domain\Event\AdministratorRegranted;
use App\Administration\Domain\Event\AdministratorRevoked;
use App\Administration\Domain\Event\RoleAssignedToAdministrator;
use App\Administration\Domain\Event\RoleUnassignedFromAdministrator;
use App\Administration\Domain\Exception\AdministratorAlreadyActive;
use App\Administration\Domain\Exception\AdministratorAlreadyRevoked;
use App\Administration\Domain\ValueObject\Actor;
use App\Administration\Domain\ValueObject\AdministratorId;
use App\Administration\Domain\ValueObject\AdministratorStanding;
use App\Administration\Domain\ValueObject\AdministratorTenureId;
use App\Administration\Domain\ValueObject\AssignedRoles;
use App\Administration\Domain\ValueObject\RankId;
use App\Administration\Domain\ValueObject\RevocationReason;
use App\Administration\Domain\ValueObject\RoleId;
use App\Administration\Domain\ValueObject\SignInAccountId;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Psr\Clock\ClockInterface;

/**
 * A member of staff, distinct from both the {@see \App\Users\Domain\User}
 * sign-in account they authenticate with (App\Users owns that) and any
 * public household member they might separately be (App\Households owns
 * that) — three tables, no shared row, and no foreign key across either
 * boundary. Being an administrator is the presence of this aggregate with
 * an open tenure, not a nullable column on a shared row.
 *
 * Carries exactly one {@see RankId} and zero or more directly assigned
 * {@see RoleId}s. There is no seniority or rank-value field here — that
 * lives solely on {@see Rank} — and no path that grants a privilege to
 * an individual: a privilege only ever reaches an administrator through
 * a role, and a role only ever reaches them through their rank or a
 * direct assignment.
 *
 * Lifecycle is a list of {@see AdministratorTenure} periods rather than
 * four nullable columns: {@see self::revoke()} closes the current tenure
 * without erasing it, {@see self::regrant()} opens a new one, and
 * {@see self::standing()} — derived as "active exactly when the newest
 * tenure is open" — is persisted as a denormalised column so a lookup by
 * sign-in account can filter without loading every tenure.
 *
 * Pure domain class: no Symfony or Doctrine imports beyond
 * Doctrine\Common\Collections, which this codebase treats as a domain
 * primitive on par with SPL collections (see Household's equivalent
 * docblock) so the aggregate can hold its child entities in a
 * Doctrine-mappable Collection.
 */
final class Administrator
{
    use AggregateRoot;

    private AdministratorId $id;
    private SignInAccountId $signInAccountId;
    private RankId $rankId;
    private AdministratorStanding $standing;

    /** @var Collection<int, AdministratorTenure> */
    private Collection $tenures;

    /** @var Collection<int, AdministratorRoleAssignment> */
    private Collection $roleAssignments;

    /**
     * Doctrine optimistic-lock version. Maintained by the ORM; never
     * mutated by domain code. Concurrent saves surface as
     * {@see \Doctrine\ORM\OptimisticLockException}, which
     * {@see \App\Administration\Infrastructure\Persistence\Doctrine\DoctrineAdministrators::save()}
     * translates into {@see \App\Administration\Domain\Exception\ConcurrentAdministratorModification}.
     */
    private int $version = 0;

    private function __construct()
    {
        $this->tenures = new ArrayCollection();
        $this->roleAssignments = new ArrayCollection();
    }

    /**
     * Grants staff status to a sign-in account, opening its first tenure.
     * $tenureId is generated by the same {@see IdentityGenerator} call
     * site as $id — the Implementation Plan's factory signature omits it
     * for brevity, but a tenure is itself an identified child entity
     * (see AdministratorTenure), so its id is supplied up front exactly
     * as {@see Household::register()} supplies its primary member's
     * MemberId rather than generating it internally.
     */
    public static function grant(
        AdministratorId $id,
        SignInAccountId $signInAccountId,
        RankId $rankId,
        AdministratorTenureId $tenureId,
        Actor $actor,
        ClockInterface $clock,
    ): self {
        $administrator = new self();
        $administrator->id = $id;
        $administrator->signInAccountId = $signInAccountId;
        $administrator->rankId = $rankId;
        $administrator->standing = AdministratorStanding::Active;

        $grantedAt = $clock->now();
        $administrator->tenures->add(new AdministratorTenure($tenureId, $administrator, $actor, $grantedAt));
        $administrator->recordThat(new AdministratorGranted($id, $signInAccountId, $rankId, $actor, $grantedAt));

        return $administrator;
    }

    public function id(): AdministratorId
    {
        return $this->id;
    }

    public function signInAccountId(): SignInAccountId
    {
        return $this->signInAccountId;
    }

    public function rankId(): RankId
    {
        return $this->rankId;
    }

    /**
     * Projects the mapped {@see AdministratorRoleAssignment} child rows
     * into a value object, mirroring {@see \App\Users\Domain\User::credential()}'s
     * relationship to its own mapped scalars: this is a read projection,
     * not itself a mapped column.
     */
    public function assignedRoles(): AssignedRoles
    {
        return AssignedRoles::of(...array_map(
            static fn (AdministratorRoleAssignment $assignment): RoleId => $assignment->roleId(),
            $this->roleAssignments->toArray(),
        ));
    }

    /**
     * Returns a defensive copy: each {@see AdministratorTenure} is cloned
     * so callers cannot close a tenure through the returned instance
     * without going through {@see self::revoke()}. Same treatment as
     * {@see Household::members()}.
     *
     * @return list<AdministratorTenure>
     */
    public function tenures(): array
    {
        return array_values(array_map(
            static fn (AdministratorTenure $tenure): AdministratorTenure => clone $tenure,
            $this->tenures->toArray(),
        ));
    }

    public function standing(): AdministratorStanding
    {
        return $this->standing;
    }

    public function isActive(): bool
    {
        return $this->standing === AdministratorStanding::Active;
    }

    public function version(): int
    {
        return $this->version;
    }

    /**
     * Closes the current open tenure. A second call without an
     * intervening {@see self::regrant()} throws — an operator retrying a
     * revoke must know nothing happened, not believe it succeeded again.
     *
     * @throws AdministratorAlreadyRevoked when this administrator is
     *         already revoked.
     */
    public function revoke(RevocationReason $reason, Actor $actor, ClockInterface $clock): void
    {
        $this->guardIsActive();

        $now = $clock->now();
        $this->currentTenure()->close($reason, $actor, $now);
        $this->standing = AdministratorStanding::Revoked;

        $this->recordThat(new AdministratorRevoked($this->id, $reason, $actor, $now));
    }

    /**
     * Re-grants staff status to a previously revoked administrator by
     * opening a new tenure; the closed tenure this leaves behind is
     * never overwritten, so "when did they leave and come back" stays
     * answerable from history. See {@see self::grant()} on why $tenureId
     * is supplied rather than generated internally.
     *
     * @throws AdministratorAlreadyActive when this administrator is
     *         already active.
     */
    public function regrant(AdministratorTenureId $tenureId, Actor $actor, ClockInterface $clock): void
    {
        if ($this->isActive()) {
            throw AdministratorAlreadyActive::for($this->id);
        }

        $grantedAt = $clock->now();
        $this->tenures->add(new AdministratorTenure($tenureId, $this, $actor, $grantedAt));
        $this->standing = AdministratorStanding::Active;

        $this->recordThat(new AdministratorRegranted($this->id, $actor, $grantedAt));
    }

    /**
     * Idempotent: a no-op (records no event) when $rankId is already the
     * current rank.
     */
    public function changeRankTo(RankId $rankId, Actor $actor, ClockInterface $clock): void
    {
        if ($this->rankId->equals($rankId)) {
            return;
        }

        $previousRankId = $this->rankId;
        $this->rankId = $rankId;
        $this->recordThat(new AdministratorRankChanged($this->id, $previousRankId, $rankId, $actor, $clock->now()));
    }

    /**
     * Idempotent: a no-op (records no event) when $roleId is already
     * directly assigned.
     */
    public function assignRole(RoleId $roleId, Actor $actor, ClockInterface $clock): void
    {
        if ($this->assignedRoles()->contains($roleId)) {
            return;
        }

        $this->roleAssignments->add(new AdministratorRoleAssignment($this, $roleId, $clock->now()));
        $this->recordThat(new RoleAssignedToAdministrator($this->id, $roleId, $actor, $clock->now()));
    }

    /**
     * Idempotent: a no-op (records no event) when $roleId is not
     * currently assigned.
     */
    public function unassignRole(RoleId $roleId, Actor $actor, ClockInterface $clock): void
    {
        $assignment = $this->roleAssignmentFor($roleId);

        if ($assignment === null) {
            return;
        }

        $this->roleAssignments->removeElement($assignment);
        $this->recordThat(new RoleUnassignedFromAdministrator($this->id, $roleId, $actor, $clock->now()));
    }

    /**
     * @throws AdministratorAlreadyRevoked when this administrator is
     *         already revoked.
     */
    private function guardIsActive(): void
    {
        if (!$this->isActive()) {
            throw AdministratorAlreadyRevoked::for($this->id);
        }
    }

    /**
     * The invariant this class maintains — exactly one open tenure while
     * standing is Active, none while Revoked — makes the "not found"
     * branch unreachable from any public method (guardIsActive() always
     * runs first), but the exception still names the state precisely:
     * no open tenure is, by definition, the revoked state.
     *
     * @throws AdministratorAlreadyRevoked when no tenure is currently open.
     */
    private function currentTenure(): AdministratorTenure
    {
        foreach ($this->tenures as $tenure) {
            if ($tenure->isOpen()) {
                return $tenure;
            }
        }

        throw AdministratorAlreadyRevoked::for($this->id);
    }

    private function roleAssignmentFor(RoleId $roleId): ?AdministratorRoleAssignment
    {
        foreach ($this->roleAssignments as $assignment) {
            if ($assignment->roleId()->equals($roleId)) {
                return $assignment;
            }
        }

        return null;
    }
}
